#!/usr/bin/env python3
"""Build data/names_tr.json: the Turkish common name of each species.json taxon.

Sources & Taxonomy:
- Türkiye Bitkileri Listesi (Damarlı Bitkiler), Prof. Dr. Adil Güner et al., Nezahat Gökyiğit Botanik Bahçesi / TÜBİVES
- Türkçe Bitki Adları Sözlüğü, Prof. Dr. Turhan Baytop, Türk Dil Kurumu (TDK)
- T.C. Tarım ve Orman Bakanlığı / Orman Genel Müdürlüğü (OGM) Ağaç ve Çalı Taksonomisi
- Vikiveri (Wikidata) & Türkçe Vikipedi botanik maddeleri ve yaygın isim taksonomi kayıtları

Output format:
{"<species id>": {"nome": "saplı meşe", "aka": ["meşe", "adi meşe"]}}
"""
import collections
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPECIES = ROOT / "data" / "species.json"
OUT = ROOT / "data" / "names_tr.json"

# Curated dictionary for species in EcoCrop / species.json
# Format: "Scientific Name": "Primary Turkish Name|Alias 1|Alias 2..."
CURATED = {
    # --- Trees & Shrubs (Ağaçlar ve Çalılar) ---
    "Abies alba": "ak göknar|göknar|köknar",
    "Abies amabilis": "pasifik göknarı|göknar",
    "Abies balsamea": "balsam göknarı|balsam köknarı|göknar",
    "Abies concolor": "gümüşi göknar|kolorado göknarı|göknar",
    "Abies pindrow": "pindrow göknarı|himalaya göknarı|göknar",
    "Abies nordmanniana": "doğu karadeniz göknarı|kafkas göknarı|göknar|köknar",
    "Abies cilicica": "toros göknarı|göknar|köknar",
    "Abroma augustum": "şeytan pamuğu",
    "Actinidia arguta": "minyatür kivi|sarmaşık kivi",
    "Actinidia chinensis": "kivi|çin bektaşi üzümü|kivi meyvesi",
    "Actinidia deliciosa": "kivi|kültür kivisi",
    "Adonis vernalis": "bahar keklikotu|keklikotu|kan damlası",
    "Ailanthus altissima": "kokarağaç|cennet ağacı|çin kokarağacı",
    "Ailanthus excelsa": "hint kokarağacı|kokarağaç",
    "Ailanthus grandis": "büyük kokarağaç|kokarağaç",
    "Bauhinia purpurea": "mor orkide ağacı|orkide ağacı",
    "Bauhinia variegata": "alacalı orkide ağacı|orkide ağacı",
    "Caragana arborescens": "sarı akasya|çalı akasyası|sibirya bezelye çalısı",
    "Chenopodium album": "sirken|ak kazayağı|akpancar",
    "Chenopodium bonus-henricus": "yabani ıspanak|iyi kral henry otu",
    "Chenopodium quinoa": "kinoa|peru kinoası",
    "Euterpe edulis": "juçara palmiyesi|palmiye kalbi",
    "Euterpe oleracea": "açai|açai palmiyesi",
    "Fortunella japonica": "kamkat|yuvarlak kumkuat",
    "Fortunella margarita": "kamkat|oval kumkuat",
    "Lagerstroemia indica": "oya ağacı|hint leylağı",
    "Lagerstroemia speciosa": "kraliçe oya ağacı|büyük oya ağacı",
    "Phalaris arundinacea": "kamışsı kuşyemi|boylu kuşotu",
    "Phalaris canariensis": "kuşyemi|kanarya otu",
    "Quercus agrifolia": "kaliforniya meşesi|meşe",
    "Quercus alba": "ak meşe|beyaz meşe|meşe",
    "Quercus bicolor": "bataklık ak meşesi|meşe",
    "Quercus chrysolepis": "kanyon meşesi|meşe",
    "Quercus dumosa": "çalı meşesi|meşe",
    "Quercus incana": "mavi meşe|meşe",
    "Quercus suber": "mantar meşesi|mantar ağacı|meşe",
    "Quercus virginiana": "canlı meşe|güney meşesi|meşe",
    "Acacia abyssinica": "habeş akasyası|akasya",
    "Acacia acuminata": "ahududu akasyası|akasya",
    "Acacia aneura": "mulga akasyası|akasya",
    "Acacia auriculiformis": "kulaklı akasya|akasya",
    "Acacia dealbata": "gümüşi akasya|mimoza|sarı mimoza",
    "Acacia decurrens": "yeşil akasya|erken siyah akasya|akasya",
    "Acacia farnesiana": "tatlı akasya|amber akasyası|farnesiana",
    "Acacia karroo": "tatlı dikenli akasya|karoo akasyası|akasya",
    "Acacia mangium": "mangiyum akasyası|orman akasyası|akasya",
    "Acacia mearnsii": "kara akasya|siyah akasya|tannin akasyası",
    "Acacia melanoxylon": "avustralya karaağacı|siyah akasya|avustralya akasyası",
    "Acacia nilotica": "arap akasyası|nil akasyası|zamk akasyası",
    "Acacia pycnantha": "altın akasya|avustralya altın akasyası",
    "Acacia saligna": "mavi yapraklı akasya|kıbrıs akasyası|sarı akasya",
    "Acacia senegal": "arap zamkı ağacı|senegal akasyası",
    "Acacia seyal": "kırmızı akasya|seyal akasyası",
    "Acacia tortilis": "şemsiye akasyası|çöl akasyası",
    "Acanthus mollis": "ayıpençesi|akantus",
    "Acca sellowiana": "kaymak ağacı|feijoa",
    "Acer caesium": "himalaya akçaağacı|akçaağaç",
    "Acer saccharum": "şeker akçaağacı|akçaağaç",
    "Acer pseudoplatanus": "dağ akçaağacı|çınar yapraklı akçaağaç|akçaağaç",
    "Acer platanoides": "ova akçaağacı|çınar yapraklı akçaağaç|akçaağaç",
    "Acer campestre": "ova akçaağacı|akçaağaç",
    "Acrocarpus fraxinifolius": "kırmızı sedir ağacı|dişbudak yapraklı akrokarpos",
    "Adansonia digitata": "baobab|maymun ekmeği ağacı",
    "Adenanthera pavonina": "mercan ağacı|kırmızı sandal ağacı",
    "Aegle marmelos": "bael meyvesi|hint ayvası|marmelos",
    "Afzelia africana": "afrika maunu|afzelia",
    "Afzelia quanzensis": "maun ağacı|afzelia",
    "Agathis robusta": "kauri çamı|queensland kaurisi",
    "Albizia chinensis": "çin gülibrişimi|ipek ağacı",
    "Albizia falcataria": "falkatarya gülibrişimi|moluk gülibrişimi",
    "Albizia julibrissin": "gülibrişim|ipek ağacı|iran akasyası",
    "Albizia lebbeck": "lebbek ağacı|sarı gülibrişim|dilsizler ağacı",
    "Albizia procera": "ak gülibrişim|beyaz siris",
    "Aleurites moluccana": "hint cevizi|mum ağacı|kandil ağacı",
    "Alnus cordata": "napoli kızılağacı|italyan kızılağacı|kızılağaç",
    "Alnus glutinosa": "adi kızılağaç|yapışkan kızılağaç|kızılağaç",
    "Alnus incana": "boz kızılağaç|gri kızılağaç|kızılağaç",
    "Alnus rubra": "kırmızı kızılağaç|oregon kızılağacı|kızılağaç",
    "Annona cherimola": "çerimoya|krem elması",
    "Annona muricata": "graviola|dikenli incir ağacı|ekşi guanabana",
    "Annona reticulata": "öküzgözü|krem elması",
    "Annona squamosa": "şeker elması|anon",
    "Araucaria angustifolia": "brezilya arokaryası|parana çamı|arokarya",
    "Araucaria araucana": "şili arokaryası|maymun çıkmaz ağacı|arokarya",
    "Araucaria bidwillii": "bunya çamı|bunya arokaryası",
    "Araucaria cunninghamii": "hoop çamı|koloni arokaryası",
    "Araucaria heterophylla": "norfolk çamı|salon çamı|arokarya",
    "Arbutus unedo": "kocayemiş|dağ çileği|davulga",
    "Arbutus andrachne": "sandal ağacı|kırmızı kocayemiş",
    "Artocarpus altilis": "ekmek ağacı|ekmek meyvesi",
    "Artocarpus heterophyllus": "jak meyvesi|jackfruit|jak ağacı",
    "Avicennia marina": "gri mangrov|deniz mangrovu",
    "Azadirachta indica": "tespih ağacı|neem ağacı|nim ağacı",
    "Betula pendula": "siğilli huş|adi huş|ak huş|huş ağacı",
    "Betula pubescens": "tüylü huş|huş ağacı",
    "Broussonetia papyrifera": "kağıt dutu|kağıt ağacı",
    "Calocedrus decurrens": "kaliforniya su sediri|su sediri",
    "Calophyllum inophyllum": "tamanu ağacı|iskenderiye defnesi",
    "Capparis spinosa": "kapari|kebere|gebre otu",
    "Carpinus betulus": "adi gürgen|gürgen",
    "Carpinus orientalis": "doğu gürgeni|gürgen",
    "Carya illinoinensis": "pekan cevizi|pikan cevizi|amerikan cevizi",
    "Carya ovata": "kabuklu hikori cevizi|hikori",
    "Cassia fistula": "hıyarşembe|altın yağmuru|hint laburnumu",
    "Castanea crenata": "japon kestanesi|kestane",
    "Castanea dentata": "amerikan kestanesi|kestane",
    "Castanea mollissima": "çin kestanesi|kestane",
    "Castanea sativa": "kestane|anadolu kestanesi|tatlı kestane",
    "Casuarina cunninghamiana": "nehir kazuarini|demir ağacı",
    "Casuarina equisetifolia": "sahil kazuarini|kazuarina|demir ağacı",
    "Casuarina glauca": "bataklık kazuarini|kazuarina",
    "Cedrela odorata": "kokulu sedrela|ispanyol sediri",
    "Cedrus atlantica": "atlas sediri|sedir",
    "Cedrus deodara": "himalaya sediri|deodar sediri",
    "Cedrus libani": "toros sediri|lübnan sediri|sedir",
    "Celtis australis": "adi çitlembik|çitlembik|dağdagan",
    "Celtis occidentalis": "batı çitlembiği|çitlembik",
    "Ceratonia siliqua": "keçiboynuzu|harnup",
    "Cercis siliquastrum": "erguvan|yabani keçiboynuzu",
    "Chamaecyparis lawsoniana": "lawson yalancı servisi|yalancı servi",
    "Cinchona pubescens": "kınakına ağacı|kınakına",
    "Cinnamomum camphora": "kafur ağacı|kafur",
    "Cinnamomum verum": "seyelan tarçını|hakiki tarçın|tarçın ağacı",
    "Citrus aurantiifolia": "misket limonu|laym",
    "Citrus aurantium": "turunç|acı portakal",
    "Citrus grandis": "pomelo|ağaç kavunu|şadok",
    "Citrus limon": "limon|kültür limonu",
    "Citrus medica": "ağaç kavunu|sedir elması",
    "Citrus paradisi": "greyfurt|altıntop",
    "Citrus reticulata": "mandalina|mandalin",
    "Citrus sinensis": "portakal|tatlı portakal",
    "Cocos nucifera": "hindistan cevizi|hindistan cevizi palmiyesi",
    "Coffea arabica": "arabica kahvesi|kahve ağacı|kahve",
    "Coffea canephora": "robusta kahvesi|kahve",
    "Coffea liberica": "liberya kahvesi|kahve",
    "Corylus avellana": "fındık|adi fındık|tombul fındık",
    "Corylus colurna": "türk fındığı|ağaç fındığı",
    "Corylus maxima": "lombardiya fındığı|iri fındık",
    "Cryptomeria japonica": "japon kriptomeryası|japon sediri",
    "Cunninghamia lanceolata": "çin köknarı|kuningamiya",
    "Cupressus arizonica": "arizona servisi|mavi servi",
    "Cupressus macrocarpa": "monterey servisi|limon servisi",
    "Cupressus sempervirens": "akdeniz servisi|adi servi|kara servi",
    "Cydonia oblonga": "ayva|kültür ayvası",
    "Dalbergia latifolia": "hint gül ağacı|doğu hindistan pelesengi",
    "Dalbergia melanoxylon": "afrika siyah ağacı|afrika abanozu",
    "Dalbergia sissoo": "sisu ağacı|kuzey hindistan pelesengi",
    "Diospyros kaki": "trabzon hurması|cennet hurması|japon hurması",
    "Diospyros lotus": "kara hurma|yabani trabzon hurması",
    "Elaeis guineensis": "afrika yağ palmiyesi|yağ palmiyesi",
    "Eriobotrya japonica": "malta eriği|yeni dünya|muşmula",
    "Eucalyptus camaldulensis": "kırmızı okaliptüs|okaliptüs|sıtma ağacı",
    "Eucalyptus citriodora": "limon kokulu okaliptüs|okaliptüs",
    "Eucalyptus deglupta": "gökkuşağı okaliptüsü|okaliptüs",
    "Eucalyptus globulus": "mavi okaliptüs|tasmanya mavi okaliptüsü",
    "Eucalyptus grandis": "büyük okaliptüs|gül okaliptüsü",
    "Eucalyptus robusta": "bataklık maunu okaliptüsü|okaliptüs",
    "Eucalyptus tereticornis": "orman okaliptüsü|okaliptüs",
    "Eucalyptus viminalis": "şerit okaliptüs|okaliptüs",
    "Fagus grandifolia": "amerikan kayını|kayın",
    "Fagus orientalis": "doğu kayını|kayın",
    "Fagus sylvatica": "avrupa kayını|adi kayın|kayın",
    "Ficus benjamina": "benjamin|ağlayan incir",
    "Ficus carica": "incir|akdeniz inciri|adi incir",
    "Ficus elastica": "kauçuk ağacı|lastik ağacı",
    "Ficus microcarpa": "küçük yapraklı incir|çin inciri",
    "Ficus religiosa": "kutsal incir|bodhi ağacı|kutsal bo ağacı",
    "Ficus sycomorus": "firavun inciri|şikomor inciri",
    "Fraxinus americana": "amerikan dişbudağı|ak dişbudak",
    "Fraxinus excelsior": "adi dişbudak|dişbudak ağacı",
    "Fraxinus ornus": "çiçekli dişbudak|manna dişbudağı",
    "Ginkgo biloba": "mabet ağacı|ginkgo|gümüş kayısı",
    "Gleditsia triacanthos": "üç dikenli yalancı keçiboynuzu|glediçya",
    "Grevillea robusta": "ipek meşesi|grevilya",
    "Hevea brasiliensis": "kauçuk ağacı|para kauçuğu",
    "Ilex paraguariensis": "mate çayı ağacı|yerba mate",
    "Jacaranda mimosifolia": "jakaranda|mavi jakaranda",
    "Juglans cinerea": "gri ceviz|tereyağı cevizi",
    "Juglans nigra": "kara ceviz|siyah ceviz",
    "Juglans regia": "ceviz|adi ceviz|anadolu cevizi",
    "Juniperus communis": "adi ardıç|ardıç",
    "Juniperus excelsa": "boylu ardıç|ardıç",
    "Juniperus oxycedrus": "katran ardıcı|dikenli ardıç",
    "Juniperus virginiana": "virjinya ardıcı|kırmızı sedir",
    "Khaya senegalensis": "senegal maunu|afrika maunu",
    "Laburnum anagyroides": "sarı salkım|altın yağmuru",
    "Larix decidua": "avrupa melezi|melez çamı",
    "Larix kaempferi": "japon melezi|melez çamı",
    "Laurus nobilis": "akdeniz defnesi|defne|tehnel",
    "Liquidambar orientalis": "anadolu sığla ağacı|günlük ağacı|sığla",
    "Liquidambar styraciflua": "amerikan sığla ağacı|sığla",
    "Liriodendron tulipifera": "lale ağacı|amerikan lale ağacı",
    "Macadamia integrifolia": "makademya fındığı|avustralya fındığı",
    "Maclura pomifera": "yalancı portakal ağacı|ayı elması",
    "Magnolia grandiflora": "büyük çiçekli manolya|manolya",
    "Malus domestica": "elma|kültür elması|adi elma",
    "Malus sylvestris": "yabani elma|orman elması",
    "Mangifera indica": "mango|hint mangosu",
    "Melaleuca alternifolia": "çay ağacı|melaleuka",
    "Melia azedarach": "tespih ağacı|hint leylağı",
    "Mespilus germanica": "muşmula|döngel|beşbıyık",
    "Morus alba": "ak dut|beyaz dut|dut",
    "Morus nigra": "kara dut|siyah dut|dut",
    "Morus rubra": "kırmızı dut|dut",
    "Myrtus communis": "mersin|murt|hambeles",
    "Olea europaea": "zeytin|akdeniz zeytini",
    "Paulownia tomentosa": "pavlonya|çin kavak ağacı|imparatoriçe ağacı",
    "Persea americana": "avokado|amerikan armudu",
    "Phoenix dactylifera": "hurma|hurma ağacı|çöl hurması",
    "Phoenix canariensis": "kanarya hurması|palmiye",
    "Picea abies": "avrupa ladini|adi ladin|ladin",
    "Picea orientalis": "doğu ladini|kafkas ladini|ladin",
    "Picea pungens": "mavi ladin|kolorado ladini",
    "Picea sitchensis": "sitka ladini|ladin",
    "Pinus brutia": "kızılçam|türk çamı|çam",
    "Pinus canariensis": "kanarya çamı|çam",
    "Pinus cembra": "isviçre taş çamı|cembra çamı",
    "Pinus contorta": "bükümlü sahil çamı|çam",
    "Pinus halepensis": "halep çamı|çam",
    "Pinus nigra": "karaçam|avusturya çamı|çam",
    "Pinus palustris": "uzun yapraklı çam|çam",
    "Pinus pinaster": "sahil çamı|deniz çamı|yıldız çamı",
    "Pinus pinea": "fıstık çamı|çam fıstığı ağacı",
    "Pinus ponderosa": "sarı çam|batı sarıçamı|ağır çam",
    "Pinus radiata": "monterey çamı|radyata çamı",
    "Pinus strobus": "veymut çamı|akçam|doğu beyaz çamı",
    "Pinus sylvestris": "sarıçam|orman çamı|kuzey çamı",
    "Pinus taeda": "loblolly çamı|orman çamı",
    "Pistacia atlantica": "atlas sakız ağacı|melengiç",
    "Pistacia lentiscus": "sakız ağacı|damla sakızı çalısı",
    "Pistacia terebinthus": "menengiç|çitlembik|çedene",
    "Pistacia vera": "antep fıstığı|şam fıstığı|fıstık ağacı",
    "Platanus occidentalis": "batı çınarı|amerikan çınarı",
    "Platanus orientalis": "doğu çınarı|çınar ağacı|anadolu çınarı",
    "Platanus x acerifolia": "londra çınarı|akçaağaç yapraklı çınar",
    "Populus alba": "ak kavak|beyaz kavak|kavak",
    "Populus deltoides": "kara kavak|amerikan kavağı",
    "Populus nigra": "kara kavak|servi kavağı|kavak",
    "Populus tremula": "titrek kavak|kavak",
    "Prosopis cineraria": "ghaf ağacı|çöl çalı akasyası",
    "Prosopis juliflora": "mesquite ağacı|çöl çalısı",
    "Prunus amygdalus": "badem|tatlı badem|badem ağacı",
    "Prunus armeniaca": "kayısı|adi kayısı",
    "Prunus avium": "kiraz|tatlı kiraz",
    "Prunus cerasifera": "can eriği|kiraz eriği",
    "Prunus cerasus": "vişne|ekşi kiraz",
    "Prunus domestica": "erik|avrupa eriği|mürdüm eriği",
    "Prunus dulcis": "badem|kültür bademi",
    "Prunus mahaleb": "mahlep|idris ağacı",
    "Prunus padus": "kuş kirazı|gevele",
    "Prunus persica": "şeftali|nektarin",
    "Prunus salicina": "japon eriği|erik",
    "Prunus spinosa": "çakal eriği|gövem|yabani erik",
    "Pseudotsuga menziesii": "duglas göknarı|oregon çamı|yalancı köknar",
    "Psidium guajava": "guava|sarı guava",
    "Punica granatum": "nar|nar ağacı",
    "Pyrus communis": "armut|adi armut|avrupa armudu",
    "Pyrus elaeagrifolia": "ahlat|yabani armut",
    "Pyrus pyrifolia": "nashi armudu|asya armudu|japon armudu",
    "Quercus cerris": "saçlı meşe|türk meşesi|meşe",
    "Quercus coccifera": "kermes meşesi|kızılmeşe",
    "Quercus frainetto": "macar meşesi|meşe",
    "Quercus ilex": "pırnal meşe|herdemyeşil meşe",
    "Quercus infectoria": "mazı meşesi|meşe",
    "Quercus petraea": "sapsız meşe|kaya meşesi|meşe",
    "Quercus pubescens": "tüylü meşe|meşe",
    "Quercus robur": "saplı meşe|adi meşe|meşe",
    "Quercus rubra": "kırmızı meşe|amerikan kızıl meşesi",
    "Quercus suber": "mantar meşesi|mantar ağacı",
    "Quercus velutina": "kara meşe|boyacı meşesi",
    "Quercus virginiana": "canlı meşe|güney meşesi",
    "Rhamnus cathartica": "akdiken|cehri",
    "Rhus coriaria": "sumak|derici sumağı",
    "Robinia pseudoacacia": "yalancı akasya|beyaz salkım",
    "Salix alba": "ak söğüt|beyaz söğüt|söğüt",
    "Salix babylonica": "salkım söğüt|söğüt",
    "Salix caprea": "keçi söğüdü|söğüt",
    "Salix fragilis": "gevrek söğüt|söğüt",
    "Sambucus nigra": "kara mürver|mürver ağacı",
    "Schinus molle": "yalancı karabiber ağacı|peru biber ağacı",
    "Schinus terebinthifolius": "brezilya biber ağacı|pembe biber",
    "Sequoiadendron giganteum": "dev sekoya|mamut ağacı",
    "Sequoia sempervirens": "sahil sekoyası|kızılçam sekoyası",
    "Sorbus aucuparia": "kuş üvezi|üvez ağacı",
    "Sorbus domestica": "üvez|adi üvez",
    "Swietenia macrophylla": "büyük yapraklı maun|honduras maunu",
    "Swietenia mahogani": "küba maunu|amerikan maunu",
    "Syzygium aromaticum": "karanfil ağacı|baharat karanfili",
    "Syzygium cumini": "jambolan|kara erik|cava eriği",
    "Tamarindus indica": "demirhindi|hint hurması",
    "Tamarix gallica": "fransız ılgını|ılgın ağacı",
    "Taxodium distichum": "bataklık servisi|porsuk servisi",
    "Taxus baccata": "adi porsuk|porsuk ağacı",
    "Tectona grandis": "tik ağacı|hint meşesi|teak",
    "Tetraclinis articulata": "sandarak ağacı|berberi mazısı",
    "Theobroma cacao": "kakao ağacı|kakao",
    "Thuja occidentalis": "batı mazısı|hayat ağacı",
    "Thuja orientalis": "doğu mazısı|çin mazısı",
    "Tilia cordata": "küçük yapraklı ıhlamur|ıhlamur",
    "Tilia platyphyllos": "büyük yapraklı ıhlamur|ıhlamur",
    "Tilia tomentosa": "gümüşi ıhlamur|ıhlamur",
    "Toona ciliata": "avustralya kırmızı sediri|toona",
    "Tsuga canadensis": "kanada sugu|doğu sugu",
    "Tsuga heterophylla": "batı sugu|hemlok köknarı",
    "Ulmus americana": "amerikan karaağacı|karaağaç",
    "Ulmus glabra": "dağ karaağacı|karaağaç",
    "Ulmus minor": "ova karaağacı|adi karaağaç|karaağaç",
    "Ulmus pumila": "sibirya karaağacı|cüce karaağaç",
    "Vitex agnus-castus": "hayıt|ayıt|keşiş biberi",
    "Vitis vinifera": "asma|üzüm|kültür asması",
    "Ziziphus jujuba": "hünnap|çin hurması|çiğde",
    "Ziziphus spina-christi": "isa dikeni|sidr ağacı",

    # --- Crops, Vegetables & Field Plants (Tarla, Sebze ve Tarım Bitkileri) ---
    "Abelmoschus esculentus": "bamya",
    "Abelmoschus manihot": "hibiskus bamyası",
    "Abelmoschus moschatus": "miskeotu|misk bamyası",
    "Abutilon theophrasti": "imam pamuğu|çin jütü",
    "Aegilops speltoides": "buğdayotu",
    "Aeschynomene americana": "eklem fiği|amerikan fiği",
    "Agaricus bisporus": "kültür mantarı|beyaz şapkalı mantar",
    "Agave americana": "sabır otu|agav|yüzyıl çiçeği",
    "Agave sisalana": "sisal keneviri|sisal",
    "Agrostis capillaris": "ince tavusotu|kırmızı tavusotu",
    "Agrostis stolonifera": "sürüngen tavusotu|tavusotu",
    "Allium ampeloprasum": "pırasa|yabani pırasa",
    "Allium cepa": "soğan|kuru soğan",
    "Allium fistulosum": "yeşil soğan|frenk soğanı",
    "Allium porrum": "pırasa|bahçe pırasası",
    "Allium sativum": "sarımsak",
    "Allium schoenoprasum": "frenk soğanı|yaprak soğanı",
    "Allium tuberosum": "çin sarımsak otu|çin frenk soğanı",
    "Aloe vera": "tıbbi sarısabır|aloe vera",
    "Aloe arborescens": "ağaçsı sarısabır|aloe",
    "Aloe ferox": "cape sarısabırı|acı aloe",
    "Alpinia galanga": "havlıcan|büyük havlıcan",
    "Amaranthus cruentus": "kırmızı horozibiği|amarant",
    "Amaranthus hypochondriacus": "prens tüyü amarant|horozibiği",
    "Ananas comosus": "ananas",
    "Anethum graveolens": "dereotu",
    "Anthriscus cerefolium": "frenk maydanozu",
    "Apium graveolens": "kereviz|kök kereviz|sap kereviz",
    "Arachis hypogaea": "yer fıstığı|fıstık",
    "Armoracia rusticana": "bayır turpu|yaban turbu",
    "Arracacia xanthorrhiza": "peru havuç kökü|arracacha",
    "Arrhenatherum elatius": "yüksek yulafotu|çayır yulafı",
    "Artemisia absinthium": "pelin otu|acı pelin",
    "Artemisia dracunculus": "tarhun|tarhun otu",
    "Asparagus officinalis": "kuşkonmaz|tıbbi kuşkonmaz",
    "Avena sativa": "yulaf|kültür yulafı",
    "Avena fatua": "yabani yulaf",
    "Avena nuda": "çıplak yulaf",
    "Avena strigosa": "kum yulafı|siyah yulaf",
    "Basella alba": "malabar ıspanağı|hint ıspanağı",
    "Beta vulgaris": "pancar|kırmızı pancar",
    "Beta vulgaris var. cicla": "pazı|yaprak pancarı",
    "Beta vulgaris var. saccharifera": "şeker pancarı",
    "Brassica campestris": "şalgam|tarla lahanası",
    "Brassica chinensis": "çin lahanası|pak çoy",
    "Brassica juncea": "kahverengi hardal|sarepta hardalı",
    "Brassica napus": "kanola|kolza",
    "Brassica napus var. napobrassica": "rutabaga|isveç şalgamı",
    "Brassica nigra": "kara hardal|siyah hardal",
    "Brassica oleracea var. acephala": "kara lahana|yaprak lahana",
    "Brassica oleracea var. botrytis": "karnabahar",
    "Brassica oleracea var. capitata": "beyaz lahana|baş lahana|lahana",
    "Brassica oleracea var. gemmifera": "brüksel lahanası",
    "Brassica oleracea var. gongyloides": "alabaş|kohlrabi|yer lahanası",
    "Brassica oleracea var. italica": "brokoli",
    "Brassica rapa": "şalgam|turp lahanası",
    "Brassica rapa Pak Choi": "pak çoy|çin lahanası",
    "Brassica rapa var. rapifera": "şalgam turpu|şalgam",
    "Bromus inermis": "kılçıksız brom|bromotu",
    "Cajanus cajan": "güvercin bezelyesi|toor dal",
    "Camelina sativa": "ketencik|yalancı keten",
    "Cannabis sativa": "kenevir|kendir",
    "Capsicum annuum": "biber|tatlı biber|sivri biber|kapya",
    "Capsicum baccatum": "peru biberi|aji",
    "Capsicum chinense": "habanero biberi|çin biberi",
    "Capsicum frutescens": "tabasco biberi|acı çili biberi",
    "Carthamus tinctorius": "aspir|yalancı safran",
    "Carum carvi": "frenk kimyonu|karaman kimyonu",
    "Cicer arietinum": "nohut|koçbaşı nohut",
    "Cichorium endivia": "hindiba|frenk salatası|endivyen",
    "Cichorium intybus": "çikori|radika|yabani hindiba",
    "Citrullus lanatus": "karpuz",
    "Coriandrum sativum": "kişniş|aşotu",
    "Crambe abyssinica": "habeş krambesi|krambe",
    "Crocus sativus": "safran|hakiki safran",
    "Crotalaria juncea": "güneş keneviri|hint keneviri",
    "Cucumis melo": "kavun|kültür kavunu",
    "Cucumis sativus": "salatalık|hıyar",
    "Cucurbita ficifolia": "incir yapraklı kabak|siyah çekirdekli kabak",
    "Cucurbita maxima": "bal kabağı|kestane kabağı",
    "Cucurbita moschata": "bal kabağı|helvacı kabağı",
    "Cucurbita pepo": "sakız kabağı|dolmalık kabak|bal kabağı",
    "Cuminum cyminum": "kimyon|kara kimyon",
    "Curcuma longa": "zerdeçal|hint safranı",
    "Curcuma zedoaria": "cedvar|zedoarya",
    "Cymbopogon citratus": "limon otu|limon çimi",
    "Cymbopogon nardus": "sitronella|seyelan limonotu",
    "Cynara cardunculus": "enginar|yabani enginar|kardo",
    "Cynara scolymus": "enginar|bahçe enginarı",
    "Cynodon dactylon": "köpekdişi ayrığı|ayrık otu|bermuda çimi",
    "Cyperus esculentus": "çufa|yer bademi|sarı topalak",
    "Dactylis glomerata": "domuz ayrığı|parmakotu",
    "Daucus carota": "havuç|kültür havucu",
    "Digitaria eriantha": "pangola çimi|parmak darı",
    "Dioscorea alata": "kanatlı yam|mor yam",
    "Dioscorea batatas": "çin tatlı patatesi|yam",
    "Dioscorea cayenensis": "sarı yam|yam",
    "Echinochloa crus-galli": "darıcan|su darısı",
    "Echinochloa frumentacea": "japon darısı|hint darısı",
    "Elettaria cardamomum": "kakule|yeşil kakule",
    "Eleusine coracana": "kuşyemi darısı|parmak darı",
    "Eragrostis tef": "tef|teff tahılı|etiyopya tefi",
    "Eruca sativa": "roka|bahçe rokası",
    "Fagopyrum esculentum": "karabuğday|greçka",
    "Fagopyrum tataricum": "tatar karabuğdayı|acı karabuğday",
    "Festuca arundinacea": "kamışsı yumak|uzun yumak çimi",
    "Festuca pratensis": "çayır yumağı|yumakotu",
    "Festuca rubra": "kırmızı yumak|kırmızı çim yumağı",
    "Foeniculum vulgare": "rezene|arapsaçı",
    "Fragaria ananassa": "çilek|bahçe çileği",
    "Fragaria vesca": "dağ çileği|yaban çileği",
    "Glycine max": "soya fasulyesi|soya",
    "Gossypium barbadense": "mısır pamuğu|uzun lifli pamuk",
    "Gossypium herbaceum": "levant pamuğu|asya pamuğu",
    "Gossypium hirsutum": "amerikan pamuğu|yayla pamuğu",
    "Guizotia abyssinica": "nijer tohumu|ramtil",
    "Helianthus annuus": "ayçiçeği|gündöndü|ayçekirdeği",
    "Helianthus tuberosus": "yer elması|tupinambo",
    "Hibiscus cannabinus": "kenaf|hint keneviri",
    "Hibiscus sabdariffa": "rozel|hatmi|ebegümeci çayı|hibiskus",
    "Hordeum vulgare": "arpa|kültür arpası",
    "Humulus lupulus": "şerbetçiotu|bira çiçeği",
    "Indigofera tinctoria": "çivit otu|hakiki çivit",
    "Ipomoea batatas": "tatlı patates|amerikan patatesi",
    "Lablab purpureus": "lablab fasulyesi|sümbül fasulyesi",
    "Lactuca sativa": "marul|kıvırcık|salata",
    "Lagenaria siceraria": "su kabağı|asma kabağı",
    "Lathyrus sativus": "mürdümük|küşne",
    "Lens culinaris": "mercimek|yeşil mercimek|kırmızı mercimek",
    "Lepidium sativum": "tere|bahçe teresi",
    "Linum usitatissimum": "keten|tohumluk keten",
    "Lolium multiflorum": "italyan çimi|tek yıllık çim",
    "Lolium perenne": "ingiliz çimi|çok yıllık çim",
    "Lotus corniculatus": "gazal boynuzu|sarı yonca",
    "Luffa aegyptiaca": "lif kabağı|bulaşık kabağı",
    "Lupinus albus": "tatlı bakla|beyaz acıbakla|termiye",
    "Lupinus angustifolius": "mavi acıbakla|dar yapraklı lüpen",
    "Lupinus luteus": "sarı acıbakla|sarı lüpen",
    "Lycopersicon esculentum": "domates",
    "Solanum lycopersicum": "domates|kültür domatesi",
    "Majorana hortensis": "mercanköşk|tatlı mercanköşk",
    "Manihot esculenta": "manyok|tapyoka|kassava",
    "Marrubium vulgare": "bozotu|ak köpekdili",
    "Matricaria chamomilla": "tıbbi papatya|mayıs papatyası",
    "Medicago lupulina": "şerbetçi yoncası|kara yonca",
    "Medicago sativa": "yonca|kaba yonca|alfaalfa",
    "Melilotus albus": "beyaz kokulu yonca|ak taşyoncası",
    "Melilotus officinalis": "sarı kokulu yonca|tıbbi kokulu yonca",
    "Mentha piperita": "nane|tıbbi nane|biberiye nanesi",
    "Mentha pulegium": "yarpuz|yaban nanesi",
    "Mentha spicata": "kıvırcık nane|bahçe nanesi",
    "Momordica charantia": "kudret narı|acı kavun",
    "Musa acuminata": "muz|tatlı muz",
    "Musa paradisiaca": "muz|plantain|pişirme muzu",
    "Nasturtium officinale": "su teresi|göz teresi",
    "Nicotiana rustica": "yabani tütün|maraş otu|tütün",
    "Nicotiana tabacum": "tütün|kültür tütünü",
    "Nigella sativa": "çörek otu|siyah susam",
    "Ocimum basilicum": "fesleğen|reyhan",
    "Onobrychis viciifolia": "adi korunga|korunga",
    "Origanum majorana": "mercanköşk",
    "Origanum vulgare": "kekik|kara kekik|istanbul kekiği",
    "Ornithopus sativus": "serradella|kuşayağı",
    "Oryza sativa": "çeltik|pirinç",
    "Panicum miliaceum": "darı|kum darısı|ak darı",
    "Panicum virgatum": "çalı darısı|şalter çimi",
    "Papaver somniferum": "haşhaş|afyon haşhaşı",
    "Passiflora edulis": "çarkıfelek|mararkuya|tutku meyvesi",
    "Pastinaca sativa": "yabani havuç|pastinak|ak havuç",
    "Pennisetum glaucum": "inci darısı|babala darısı",
    "Petroselinum crispum": "maydanoz|yaprak maydanoz",
    "Phaseolus acutifolius": "tepary fasulyesi",
    "Phaseolus coccineus": "ateş fasulyesi|sarmaşık fasulye",
    "Phaseolus lunatus": "lima fasulyesi|ay fasulyesi",
    "Phaseolus vulgaris": "taze fasulye|kuru fasulye|fasulye",
    "Phleum pratense": "çayır kelpotu|timoti çimi",
    "Physalis peruviana": "altın çilek|güveyfeneri|yer kirazı",
    "Piper nigrum": "karabiber|beyaz biber",
    "Pisum sativum": "bezelye|bahçe bezelyesi",
    "Poa pratensis": "çayır salkımotu|kentucky maviçimi",
    "Portulaca oleracea": "semizotu|yabani semizotu",
    "Raphanus sativus": "turp|kırmızı turp|fındık turpu",
    "Rheum rhabarbarum": "ışkın|ravent|bahçe raventi",
    "Ricinus communis": "hint yağı bitkisi|keneotu",
    "Rosmarinus officinalis": "biberiye|kuşdili otu",
    "Rubus idaeus": "ahududu|ağaççileği|frambuaz",
    "Rubus fruticosus": "böğürtlen|mor böğürtlen",
    "Rumex acetosa": "kuzukulağı|ekşiot",
    "Ruta graveolens": "sedef otu|katran otu",
    "Saccharum officinarum": "şeker kamışı",
    "Salvia officinalis": "adaçayı|tıbbi adaçayı",
    "Salvia sclarea": "misk adaçayı|ayı kulağı",
    "Satureja hortensis": "çibris|bahçe kekiği|yaz geyikotu",
    "Satureja montana": "kış kekiği|dağ kekiği",
    "Secale cereale": "çavdar|kültür çavdarı",
    "Sesamum indicum": "susam|küncü",
    "Setaria italica": "italyan darısı|çin darısı|kuşyemi",
    "Sinapis alba": "beyaz hardal|sarı hardal",
    "Solanum aethiopicum": "etiopya patlıcanı",
    "Solanum melongena": "patlıcan|kemerkem",
    "Solanum muricatum": "pepino|kavun armudu",
    "Solanum tuberosum": "patates|patates yumrusu",
    "Sorghum bicolor": "süpürge darısı|sorgum|akdarı",
    "Sorghum sudanense": "sudan otu|sudan darısı",
    "Spinacia oleracea": "ıspanak|kültür ıspanağı",
    "Taraxacum officinale": "karahindiba|aslandişi",
    "Thymus vulgaris": "kekik|bahçe kekiği|adi kekik",
    "Tragopogon porrifolius": "yemlik|tekesakalı|iskorçina",
    "Trifolium alexandrinum": "iskenderiye üçgülü|mısır üçgülü",
    "Trifolium hybridum": "melez üçgül|isveç üçgülü",
    "Trifolium incarnatum": "kırmızı üçgül|kan üçgülü",
    "Trifolium pratense": "çayır üçgülü|kırmızı yonca|tavşanmemesi",
    "Trifolium repens": "ak üçgül|beyaz yonca|üçgül",
    "Trifolium resupinatum": "fars üçgülü|anadolu üçgülü",
    "Trifolium subterraneum": "yeraltı üçgülü|toprak üçgülü",
    "Trigonella foenum-graecum": "çemen otu|buyotu",
    "Triticum aestivum": "ekmeklik buğday|buğday",
    "Triticum durum": "makarnalık buğday|sert buğday",
    "Triticum monococcum": "siyez buğdayı|kaplıca buğdayı",
    "Triticum spelta": "kavuzlu buğday|dinkel buğdayı|spelta",
    "Tropaeolum majus": "latin çiçeği|frenk teresi",
    "Urtica dioica": "büyük ısırgan|ısırgan otu",
    "Vaccinium corymbosum": "yüksek boylu yaban mersini|mavi yemiş",
    "Vaccinium macrocarpon": "turna yemişi|büyük meyveli kızılcık|cranberry",
    "Vaccinium myrtillus": "yaban mersini|çobanüzümü|ayıüzümü",
    "Valerianella locusta": "kuzu kulağı salatası|tarla salatası",
    "Vanilla planifolia": "vanilya|düz yapraklı vanilya",
    "Vicia faba": "bakla|tarla baklası",
    "Vicia sativa": "adi fiğ|fiğ",
    "Vicia villosa": "tüylü fiğ|kum fiği",
    "Vigna aconitifolia": "güve fasulyesi|mat fasulyesi",
    "Vigna angularis": "azuki fasulyesi|kırmızı fasulye",
    "Vigna mungo": "urad fasulyesi|siyah maş fasulyesi",
    "Vigna radiata": "maş fasulyesi|yeşil maş",
    "Vigna subterranean": "bambara yer fıstığı",
    "Vigna unguiculata": "börülce|karagöz börülce",
    "Zea mays": "mısır|kültür mısırı",
    "Zea mays ssp. mays": "mısır|tane mısır",
    "Zea mays ssp. saccharata": "şeker mısırı|tatlı mısır",
    "Zingiber officinale": "zencefil|tıbbi zencefil",
}

# Genus level fallback names for species without explicit species-level curated entry
GENUS_FALLBACK = {
    "Abies": ("göknar", ["köknar"]),
    "Acacia": ("akasya", ["avustralya akasyası"]),
    "Acer": ("akçaağaç", []),
    "Achillea": ("civanperçemi", []),
    "Acrocarpus": ("akrokarpos", []),
    "Actinidia": ("kivi", ["sarmaşık kivi"]),
    "Adansonia": ("baobab", []),
    "Adesmia": ("adesmiya", []),
    "Adenanthera": ("mercan ağacı", []),
    "Aegilops": ("buğdayotu", []),
    "Aeschynomene": ("eklem fiği", []),
    "Agathis": ("kauri çamı", []),
    "Agave": ("sabır otu", ["agav"]),
    "Agropyron": ("ayrık otu", ["tarla ayrığı"]),
    "Agrostis": ("tavusotu", []),
    "Ailanthus": ("kokarağaç", ["cennet ağacı"]),
    "Albizia": ("gülibrişim", ["ipek ağacı"]),
    "Aleurites": ("kandil ağacı", []),
    "Allium": ("yabani soğan", ["soğan"]),
    "Alnus": ("kızılağaç", []),
    "Aloe": ("sarısabır", ["aloe"]),
    "Alysicarpus": ("alizikarpos", []),
    "Amaranthus": ("horozibiği", ["amarant"]),
    "Andropogon": ("sakalotu", ["mavi çim"]),
    "Annona": ("anon", ["krem elması"]),
    "Anogeissus": ("aksakal ağacı", []),
    "Anthyllis": ("gönen otu", []),
    "Araucaria": ("arokarya", ["salon çamı"]),
    "Arbutus": ("kocayemiş", ["dağ çileği"]),
    "Argyrodendron": ("lale meşesi", []),
    "Aristida": ("üçkılçık otu", []),
    "Arrhenatherum": ("yulafotu", []),
    "Artemisia": ("pelin otu", []),
    "Artocarpus": ("ekmek ağacı", []),
    "Asclepias": ("ipekotu", []),
    "Asparagus": ("kuşkonmaz", []),
    "Astragalus": ("geven", []),
    "Astrebla": ("mitchell çimi", []),
    "Atriplex": ("unluca", ["tuz çalısı"]),
    "Avena": ("yulaf", []),
    "Axonopus": ("halı çimi", []),
    "Baccaurea": ("rambai ağacı", []),
    "Bambusa": ("bambu", []),
    "Bauhinia": ("orkide ağacı", ["bahunya"]),
    "Betula": ("huş", ["huş ağacı"]),
    "Bothriochloa": ("mavi sakalotu", []),
    "Brachiaria": ("brakiyarya çimi", []),
    "Brassica": ("lahana", ["hardal"]),
    "Bromus": ("bromotu", ["kılçıksız brom"]),
    "Cajanus": ("güvercin bezelyesi", []),
    "Calamus": ("hintkamışı", ["rattan"]),
    "Calliandra": ("kalliyandra", ["pudra ponponu"]),
    "Callitris": ("servi çamı", []),
    "Calophyllum": ("tamanu", []),
    "Camellia": ("çay çalısı", ["kamelya"]),
    "Canavalia": ("kılıç fasulyesi", []),
    "Capparis": ("kapari", ["kebere"]),
    "Capsicum": ("biber", []),
    "Caragana": ("çalı akasyası", ["sarı akasya"]),
    "Carpinus": ("gürgen", []),
    "Carya": ("hikori cevizi", []),
    "Cassia": ("kassiya", ["altın yağmuru"]),
    "Castanea": ("kestane", []),
    "Casuarina": ("kazuarina", ["demir ağacı"]),
    "Cedrela": ("sedrela", []),
    "Cedrus": ("sedir", []),
    "Celtis": ("çitlembik", []),
    "Cenchrus": ("karanfil darısı", ["kum darısı"]),
    "Centrosema": ("kelebek bezelyesi", []),
    "Ceratonia": ("keçiboynuzu", ["harnup"]),
    "Cercis": ("erguvan", []),
    "Chenopodium": ("sirken", ["kazayağı"]),
    "Chloris": ("kloris çimi", ["rodes çimi"]),
    "Chrysophyllum": ("yıldız elması", []),
    "Cicer": ("nohut", []),
    "Cichorium": ("hindiba", []),
    "Cinchona": ("kınakına", []),
    "Cinnamomum": ("tarçın ağacı", []),
    "Citrullus": ("karpuz", []),
    "Citrus": ("turunçgil", ["narenciye"]),
    "Cleome": ("örümcek çiçeği", []),
    "Clitoria": ("mavi bezelye çiçeği", []),
    "Coffea": ("kahve", ["kahve ağacı"]),
    "Coix": ("meryemana tespihi", []),
    "Colocasia": ("gölevez", ["taro"]),
    "Corchorus": ("jüt", []),
    "Coriandrum": ("kişniş", []),
    "Corylus": ("fındık", []),
    "Cotylelobium": ("resak ağacı", []),
    "Crotalaria": ("çıngıraklı fiğ", []),
    "Cryptomeria": ("kriptomerya", ["japon sediri"]),
    "Cucumis": ("hıyar", ["kavun"]),
    "Cucurbita": ("kabak", []),
    "Cuminum": ("kimyon", []),
    "Cupressus": ("servi", []),
    "Cymbopogon": ("limonotu", []),
    "Cynara": ("enginar", []),
    "Cynodon": ("ayrık otu", ["bermuda çimi"]),
    "Cyperus": ("topalak", []),
    "Dactylis": ("domuz ayrığı", []),
    "Dalbergia": ("pelesenk ağacı", ["gül ağacı"]),
    "Daucus": ("havuç", []),
    "Dendrocalamus": ("dev bambu", []),
    "Derris": ("derris kökü", []),
    "Desmanthus": ("demet çalı fiği", []),
    "Desmodium": ("desmodyum", []),
    "Dichanthium": ("mavi halka otu", []),
    "Digitaria": ("parmak darı", []),
    "Dillenia": ("dilenya ağacı", []),
    "Dioscorea": ("yam yumrusu", ["yam"]),
    "Diospyros": ("trabzon hurması", []),
    "Dipterocarpus": ("keruing ağacı", []),
    "Echinochloa": ("darıcan", []),
    "Elaeis": ("yağ palmiyesi", []),
    "Eleusine": ("kuşyemi darısı", []),
    "Elymus": ("yabani buğdayotu", []),
    "Enterolobium": ("maymun kulağı ağacı", []),
    "Eragrostis": ("aşk çimi", ["tef"]),
    "Erica": ("funda", ["süpürge çalısı"]),
    "Eriobotrya": ("malta eriği", ["yeni dünya"]),
    "Erythrina": ("mercan ağacı", []),
    "Eucalyptus": ("okaliptüs", ["sıtma ağacı"]),
    "Eugenia": ("öjenya", []),
    "Euterpe": ("açai palmiyesi", []),
    "Fagopyrum": ("karabuğday", []),
    "Fagus": ("kayın", []),
    "Festuca": ("yumak çimi", []),
    "Ficus": ("incir", []),
    "Flindersia": ("ipek dişbudağı", []),
    "Foeniculum": ("rezene", []),
    "Fortunella": ("kamkat", ["kumkuat"]),
    "Fragaria": ("çilek", []),
    "Fraxinus": ("dişbudak", []),
    "Garcinia": ("mangostan", []),
    "Genista": ("katırtırnağı", []),
    "Ginkgo": ("mabet ağacı", ["ginkgo"]),
    "Gleditsia": ("üçdiken ağacı", []),
    "Gliricidia": ("glirisidya", ["ana ağacı"]),
    "Glycine": ("soya fasulyesi", []),
    "Gossypium": ("pamuk", []),
    "Grewia": ("greviya", []),
    "Grevillea": ("grevilya", []),
    "Guizotia": ("nijer tohumu", []),
    "Hedysarum": ("tatlı tırfıl", []),
    "Helianthus": ("ayçiçeği", []),
    "Hibiscus": ("hatmi", ["ebegümeci"]),
    "Hippophae": ("yalancı iğde", ["çıçırgan"]),
    "Holcus": ("balduva", []),
    "Hopea": ("merawan ağacı", []),
    "Hordeum": ("arpa", []),
    "Humulus": ("şerbetçiotu", []),
    "Hydnocarpus": ("şalmogra ağacı", []),
    "Hymenaea": ("jatoba", []),
    "Hypericum": ("kantaron", ["binbirdelik otu"]),
    "Ilex": ("çobanpüskülü", []),
    "Indigofera": ("çivit otu", []),
    "Inga": ("inga ağacı", []),
    "Ipomoea": ("tatlı patates", ["kahkaha çiçeği"]),
    "Ischaemum": ("örümcek çimi", []),
    "Jacaranda": ("jakaranda", []),
    "Juglans": ("ceviz", []),
    "Juniperus": ("ardıç", []),
    "Khaya": ("afrika maunu", []),
    "Lablab": ("lablab fasulyesi", []),
    "Lactuca": ("marul", []),
    "Lagenaria": ("su kabağı", []),
    "Lagerstroemia": ("oya ağacı", ["hint leylağı"]),
    "Larix": ("melez çamı", []),
    "Lathyrus": ("mürdümük", []),
    "Laurus": ("defne", []),
    "Lavandula": ("lavanta", []),
    "Lens": ("mercimek", []),
    "Leonotis": ("aslankulağı", []),
    "Lepidium": ("tere", []),
    "Lespedeza": ("çalı üçgülü", []),
    "Leucaena": ("lösenya", []),
    "Ligustrum": ("kurtbağrı", []),
    "Linum": ("keten", []),
    "Liquidambar": ("sığla ağacı", ["günlük ağacı"]),
    "Liriodendron": ("lale ağacı", []),
    "Lolium": ("çim", []),
    "Lonchocarpus": ("timbo ağacı", []),
    "Lotononis": ("lotononis", []),
    "Lotus": ("gazalboynuzu", []),
    "Luffa": ("lif kabağı", []),
    "Lupinus": ("acıbakla", ["lüpen"]),
    "Lycopersicon": ("domates", []),
    "Macadamia": ("makademya fındığı", []),
    "Macroptilium": ("siratro", []),
    "Macrotyloma": ("at fasulyesi", []),
    "Malus": ("elma", []),
    "Mangifera": ("mango", []),
    "Manihot": ("manyok", []),
    "Medicago": ("yonca", []),
    "Melaleuca": ("melaleuka", ["çay ağacı"]),
    "Melia": ("tespih ağacı", []),
    "Melilotus": ("kokulu yonca", []),
    "Mentha": ("nane", []),
    "Mespilus": ("muşmula", []),
    "Momordica": ("kudret narı", []),
    "Moringa": ("moringa", ["mucize ağaç"]),
    "Morus": ("dut", []),
    "Mucuna": ("kadife fasulye", []),
    "Musa": ("muz", []),
    "Myrica": ("mum çalısı", []),
    "Myrtus": ("mersin", ["murt"]),
    "Nasturtium": ("su teresi", []),
    "Neonotonia": ("yabani soya", []),
    "Nicotiana": ("tütün", []),
    "Nigella": ("çörekotu", []),
    "Ocimum": ("fesleğen", ["reyhan"]),
    "Olea": ("zeytin", []),
    "Onobrychis": ("korunga", []),
    "Opuntia": ("kaynanadili", ["frenk inciri"]),
    "Origanum": ("kekik", ["mercanköşk"]),
    "Ornithopus": ("serradella", []),
    "Oryza": ("pirinç", ["çeltik"]),
    "Panicum": ("darı", []),
    "Papaver": ("haşhaş", []),
    "Paspalum": ("paspalum çimi", []),
    "Passiflora": ("çarkıfelek", []),
    "Pastinaca": ("pastinak", ["ak havuç"]),
    "Paulownia": ("pavlonya", []),
    "Pennisetum": ("inci darısı", []),
    "Persea": ("avokado", []),
    "Petroselinum": ("maydanoz", []),
    "Phalaris": ("kuşyemi", ["kuşotu"]),
    "Phaseolus": ("fasulye", []),
    "Philadelphus": ("filbahri", []),
    "Phleum": ("kelpotu", ["çayır çimi"]),
    "Phoenix": ("hurma ağacı", []),
    "Phyllanthus": ("amla", []),
    "Physalis": ("altın çilek", ["güveyfeneri"]),
    "Picea": ("ladin", []),
    "Pinus": ("çam", []),
    "Piper": ("karabiber", []),
    "Pistacia": ("fıstık ağacı", ["sakız ağacı"]),
    "Pisum": ("bezelye", []),
    "Plantago": ("karnıyarık otu", ["sinirliot"]),
    "Platanus": ("çınar", []),
    "Poa": ("salkımotu", []),
    "Populus": ("kavak", []),
    "Portulaca": ("semizotu", []),
    "Prosopis": ("mesquite", []),
    "Prunus": ("erik/kiraz/badem", []),
    "Pseudotsuga": ("duglas köknarı", []),
    "Psidium": ("guava", []),
    "Pterocarpus": ("kan ağacı", []),
    "Pueraria": ("kudzu", []),
    "Punica": ("nar", []),
    "Pyrus": ("armut", []),
    "Quercus": ("meşe", []),
    "Raphanus": ("turp", []),
    "Rhamnus": ("cehri", ["akdiken"]),
    "Rheum": ("ravent", ["ışkın"]),
    "Rhododendron": ("orman gülü", ["açelya"]),
    "Rhus": ("sumak", []),
    "Ribes": ("frenk üzümü", []),
    "Ricinus": ("hintyağı bitkisi", []),
    "Robinia": ("yalancı akasya", ["beyaz salkım"]),
    "Rosa": ("gül", ["kuşburnu"]),
    "Rosmarinus": ("biberiye", []),
    "Rubus": ("böğürtlen/ahududu", []),
    "Rumex": ("kuzukulağı", []),
    "Ruta": ("sedefotu", []),
    "Saccharum": ("şeker kamışı", []),
    "Salix": ("söğüt", []),
    "Salvia": ("adaçayı", []),
    "Sambucus": ("mürver", []),
    "Sanguisorba": ("çayırdüğmesi", []),
    "Santalum": ("sandal ağacı", []),
    "Sapindus": ("sabun ağacı", []),
    "Satureja": ("dağ kekiği", []),
    "Schinus": ("yalancı karabiber", []),
    "Secale": ("çavdar", []),
    "Senna": ("sinameki", []),
    "Sequoia": ("sekoya", []),
    "Sequoiadendron": ("dev sekoya", []),
    "Sesamum": ("susam", []),
    "Sesbania": ("sesbanya", []),
    "Setaria": ("yapışkan darı", []),
    "Shorea": ("meranti ağacı", []),
    "Sida": ("sida otu", []),
    "Sinapis": ("hardal", []),
    "Smilax": ("melocan", ["saparna"]),
    "Solanum": ("itüzümü/patlıcan", []),
    "Sorghum": ("sorgum", ["süpürge darısı"]),
    "Spartium": ("katırtırnağı", []),
    "Spinacia": ("ıspanak", []),
    "Sterculia": ("kestane yapraklı ağaç", []),
    "Stipa": ("kavılca otu", []),
    "Stylosanthes": ("kalem yoncası", []),
    "Swietenia": ("maun ağacı", []),
    "Symphytum": ("karakafes otu", []),
    "Syzygium": ("mersin ağacı", []),
    "Tagetes": ("kadife çiçeği", []),
    "Tamarindus": ("demirhindi", []),
    "Tamarix": ("ılgın", []),
    "Taraxacum": ("karahindiba", []),
    "Taxodium": ("bataklık servisi", []),
    "Taxus": ("porsuk ağacı", []),
    "Tecoma": ("sarı boru çiçeği", []),
    "Tectona": ("tik ağacı", []),
    "Terminalia": ("terminalya", []),
    "Tetraclinis": ("berberi mazısı", []),
    "Theobroma": ("kakao", []),
    "Thuja": ("mazı", []),
    "Thymus": ("kekik", []),
    "Tilia": ("ıhlamur", []),
    "Toona": ("sedir ağacı", []),
    "Tragopogon": ("yemlik", []),
    "Trifolium": ("üçgül", ["yonca"]),
    "Trigonella": ("çemen otu", []),
    "Triticum": ("buğday", []),
    "Tropaeolum": ("latin çiçeği", []),
    "Tsuga": ("suk köknarı", []),
    "Typha": ("saz", ["hasırotu"]),
    "Ulex": ("dikenli katırtırnağı", []),
    "Ulmus": ("karaağaç", []),
    "Urochloa": ("para çimi", []),
    "Urtica": ("ısırgan", []),
    "Vaccinium": ("yaban mersini", []),
    "Valerianella": ("tarla salatası", []),
    "Vanilla": ("vanilya", []),
    "Vicia": ("fiğ", []),
    "Vigna": ("börülce", ["maş fasulyesi"]),
    "Vitex": ("hayıt", []),
    "Vitis": ("asma", ["üzüm"]),
    "Zea": ("mısır", []),
    "Zingiber": ("zencefil", []),
    "Ziziphus": ("hünnap", []),
    "Zoysia": ("zoysya çimi", []),
}

# Epithet patterns to combine with genus name if specific entry is missing
EPITHETS = {
    "alba": "ak",
    "albus": "ak",
    "album": "ak",
    "nigra": "kara",
    "niger": "kara",
    "nigrum": "kara",
    "rubra": "kırmızı",
    "ruber": "kırmızı",
    "rubrum": "kırmızı",
    "lutea": "sarı",
    "luteus": "sarı",
    "viridis": "yeşil",
    "sylvestris": "orman",
    "silvestris": "yabani",
    "orientalis": "doğu",
    "orientale": "doğu",
    "occidentalis": "batı",
    "occidentale": "batı",
    "australis": "güney",
    "australe": "güney",
    "borealis": "kuzey",
    "canadensis": "kanada",
    "africana": "afrika",
    "africanus": "afrika",
    "americana": "amerikan",
    "americanus": "amerikan",
    "japonica": "japon",
    "japonicus": "japon",
    "chinensis": "çin",
    "indica": "hint",
    "indicus": "hint",
    "indicum": "hint",
    "communis": "adi",
    "commune": "yaygın",
    "vulgaris": "adi",
    "vulgare": "yaygın",
    "sativa": "kültür",
    "sativus": "ekilen",
    "sativum": "kültür",
    "officinalis": "tıbbi",
    "officinale": "şifalı",
    "edulis": "yenen",
    "edule": "yenilebilir",
    "grandis": "büyük",
    "grandiflora": "büyük çiçekli",
    "parviflora": "küçük çiçekli",
    "pendula": "sarkık",
    "sempervirens": "herdemyeşil",
    "aquatica": "su",
    "maritima": "sahil",
    "montana": "dağ",
    "pratensis": "çayır",
    "arvensis": "tarla",
    "palustris": "bataklık",
    "nemoralis": "koru",
}


def clean_name(s):
    """Normalize Turkish string: lowercase, trim spaces."""
    if not s:
        return ""
    s = s.strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def binomial(sci):
    """Strip variety / subspecies to get (genus, epithet)."""
    s = re.sub(r"\s*(subsp\.|ssp\.|var\.|f\.|gr\.)\s+\S+", "", sci)
    s = s.replace("×", "").replace(" x ", " ")
    parts = s.split()
    if len(parts) < 2 or parts[1].lower() in ("sp.", "spp."):
        return parts[0], "" if parts else ("", "")
    return parts[0], parts[1].lower().rstrip(".")


def build_turkish_names():
    species_list = json.load(open(SPECIES, encoding="utf-8"))
    out = {}

    for sp in species_list:
        sid = str(sp["id"])
        sci = sp["sci"].strip()
        genus, epithet = binomial(sci)

        # 1. Exact match in CURATED
        if sci in CURATED:
            parts = [clean_name(p) for p in CURATED[sci].split("|") if p.strip()]
            if parts:
                entry = {"nome": parts[0]}
                if len(parts) > 1:
                    entry["aka"] = parts[1:]
                out[sid] = entry
                continue

        # 2. Binomial match in CURATED (without sub-taxa)
        binom_str = f"{genus} {epithet}".strip()
        if binom_str in CURATED:
            parts = [clean_name(p) for p in CURATED[binom_str].split("|") if p.strip()]
            if parts:
                entry = {"nome": parts[0]}
                if len(parts) > 1:
                    entry["aka"] = parts[1:]
                out[sid] = entry
                continue

        # 3. Genus + Epithet rule combination
        if genus in GENUS_FALLBACK:
            base_tr, akas = GENUS_FALLBACK[genus]
            if epithet in EPITHETS:
                prefix = EPITHETS[epithet]
                name = f"{prefix} {base_tr}".strip()
                entry = {"nome": name}
                combined_akas = [f"{base_tr}"] + akas
                # remove duplicates while preserving order
                entry["aka"] = list(dict.fromkeys(a for a in combined_akas if a != name))
                out[sid] = entry
                continue
            else:
                # Fallback to genus name
                entry = {"nome": base_tr}
                if akas:
                    entry["aka"] = list(akas)
                out[sid] = entry
                continue

    return out


def main():
    print(f"Building Turkish species dictionary from {SPECIES}...")
    names = build_turkish_names()
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(names, f, ensure_ascii=False, indent=None, separators=(",", ":"))
    print(f"Successfully generated {OUT} with {len(names)} translated taxa.")


if __name__ == "__main__":
    main()
